.git
.gitignore

node_modules
**/dist
coverage
.nyc_output

playwright-report
test-results
*.lcov

.env
.env.*
**/.env
**/.env.*
docker/compose.yml
docker/compose.example.yml

.vscode
.idea
*.swp
*.swo
.DS_Store
Thumbs.db

.cache
.vite
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

docker/restart.sh
docs/
